### ISSUE TITLE
[Bug] Không có file env example 

### ISSUE THREAD

**Issue by baonq-me** [TVU-OPS/UniHand#75]
Không có file env example để chạy docker compose

**Comment by tanmaiii** [comment]
Dạ, hiện tại trước khi run docker compose up -d, sẽ run lệnh `npm run genv` để hệ thống tự tạo file .env ạ, trong docs hướng dẫn cài đặt có ạ!
Còn việc tạo thêm file env example chúng em xin ghi nhận ý kiến và sẽ xem xét bổ sung ạ!
Chúng em xin trân thành cảm ơn đóng góp ý kiến của anh ạ!

**Comment by baonq-me** [comment]
Cách bạn làm không sai, nhưng thực tế muốn xem nhanh một project cần kết nối đến những service gì thì chỉ cần nhìn vào file cấu hình của nó nhé bạn.

Tương tự
https://github.com/TVU-OPS/UniHand/blob/main/nginx.conf.template

**Comment by tanmaiii** [comment]
Chúng em rất cảm ơn ý kiến đóng góp của anh ạ! Và sẽ bổ sung sớm nhất ạ!
Trân trọng!
